
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author crabman
 */
public class Lorry extends javax.swing.JFrame {
    
    String str1,str2,str3,str4,str5,str28,str29;

    /**
     * Creates new form Lorry
     */
  private static Lorry obj=null;
    
    private Lorry() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(Lorry.DO_NOTHING_ON_CLOSE);
        setIcon();
    }

    
    public static Lorry getObj(){
        if(obj==null){
            obj=new Lorry();
        }return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Result = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ΘΕΩΡΗΤΙΚΑ ΦΟΡΤΗΓΟ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("ΣΤΟΙΧΕΙΑ ΥΠΟΨΗΦΙΟΥ");

        jLabel2.setText("ΟΝΟΜΑΤΕΠΩΝΥΜΟ");

        Result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Result);

        jButton1.setText("ΑΝΑΖΗΤΗΣΗ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ΕΚΤΥΠΩΣΗ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ΚΑΘΑΡΙΣΜΟΣ ΠΕΔΙΩΝ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                 try {
            // TODO add your handling code here:
            
                                   Class.forName("org.sqlite.JDBC");
                                   String sourceURL=new String("jdbc:sqlite:driveschool.sqlite");
                            java.sql.Connection ConnectiondatabaseConnection = DriverManager.getConnection(sourceURL);
                            Statement statement=ConnectiondatabaseConnection.createStatement();
                             
                            
                            String str1=Search.getText();
                            
                            
                            if (!str1.startsWith("'"))
                                 str1 = "'" + str1;
                                 
                                
                            if (!str1.endsWith("'"))
                                 str1 = str1 + "'";
                            
                           	        	String sql="SELECT theoritical.'Ονοματεπώνυμο_Μαθητή',theoritical.`Αριθμός Πρωτοκόλλου`,theoritical.`Κατηγορία`,theoritical.Ημερομηνία_Θεωρητικού,theoritical.`Ώρα Έναρξης`,theoritical.`Ώρα Λήξης`,practical.`Ημερομηνία Πρακτικού`,practical.`Ώρα Έναρξης`,practical.`Ώρα Λήξης`FROM theoritical INNER JOIN practical ON theoritical.`Αριθμός Πρωτοκόλλου` =practical.`Αριθμός Πρωτοκόλλου` WHERE theoritical.Ονοματεπώνυμο_Μαθητή="+str1+"AND theoritical.Κατηγορία='Φορτηγό'";

                            ResultSet result=statement.executeQuery(sql);
                            if (result.next()){
                             Result.setModel(DbUtils.resultSetToTableModel(result));
                        
                            ConnectiondatabaseConnection.close();
        }else {
                                String Message="Δεν υπάρχει εγγραφή";
                     JOptionPane.showMessageDialog(null,Message); 
                            }
                 }
                 catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
                   Class.forName("org.sqlite.JDBC");
                   String sourceURL=new String("jdbc:sqlite:driveschool.sqlite");
                            java.sql.Connection ConnectiondatabaseConnection = DriverManager.getConnection(sourceURL);
                            Statement statement=ConnectiondatabaseConnection.createStatement();
                             
                            
                            String str1=Search.getText();
                            
                            
                            if (!str1.startsWith("'"))
                                 str1 = "'" + str1;
                                 
                                
                            if (!str1.endsWith("'"))
                                 str1 = str1 + "'";
	        	String sql="SELECT theoritical.`Ονοματεπώνυμο_Μαθητή`,theoritical.`Αριθμός Πρωτοκόλλου`,theoritical.`Κατηγορία`,theoritical.Ημερομηνία_Θεωρητικού,theoritical.`Ώρα Έναρξης`,theoritical.`Ώρα Λήξης`,practical.`Ημερομηνία Πρακτικού`,practical.`Ώρα Έναρξης`,practical.`Ώρα Λήξης` FROM theoritical INNER JOIN practical ON theoritical.`Αριθμός Πρωτοκόλλου` =practical.`Αριθμός Πρωτοκόλλου` WHERE theoritical.Ονοματεπώνυμο_Μαθητή="+str1+"AND theoritical.Κατηγορία='Φορτηγό'";
                            
                            ResultSet result=statement.executeQuery(sql);
                                displayresults(result);
                                 ConnectiondatabaseConnection.close();
             String Message="Το αρχείο έχει δημιουργηθεί";
               File fontFile = new File("C:/Windows/Fonts/arialuni.ttf"); 
         
                     BaseFont unicode = BaseFont.createFont(fontFile.getAbsolutePath(), BaseFont.IDENTITY_H, true);
                     Font fonty=new Font(unicode,14,Font.NORMAL);
                     Font fonty2=new Font(unicode,8,Font.NORMAL);
                Document document = new Document(); 
                  PdfWriter.getInstance(document, new FileOutputStream("Track.pdf"));
              
          
               
                    
                     document.open();
                
                   String str="                        ΑΝΑΛΥΤΙΚΗ ΩΡΙΑΙΑ ΚΑΤΑΣΤΑΣΗ ΘΕΩΡΗΤΙΚΗΣ ΕΚΠΑΙΔΕΥΣΗΣ ";        
                  
                   
                     String str51="ΟΝΟΜ/ΝΥΜΟ ΥΠΟΨΗΦΙΟΥ:"
                             + str28;
                      PdfPTable table=new PdfPTable(8);
                         table.setWidthPercentage(110);
                      PdfPCell cell33=new PdfPCell(new Paragraph(str,fonty));
                     cell33.setColspan(10);
                     table.addCell(cell33);
                     PdfPCell cell = new PdfPCell (new Paragraph (str51,fonty2));
                     cell.setColspan(2);
                     table.addCell(cell);
                    
                      String str2="Αρ.Πρωτ:Δ.Ε.Ε.:"
                              + str29;
                     
                     PdfPCell cell2 = new PdfPCell (new Paragraph (str2,fonty2));
                      cell2.setColspan(2);
                     table.addCell(cell2);
                        
                       String str3="ΚΑΤΗΓΟΡΙΑ:"
                               + " ΦΟΡΤΗΓΟ C1,C";
                     
                     PdfPCell cell3 = new PdfPCell (new Paragraph (str3,fonty2));
                      cell3.setColspan(4);
                     table.addCell(cell3);
                     
                        String str4="α/α";
                     
                     PdfPCell cell4 = new PdfPCell (new Paragraph (str4,fonty2));
                    
                      
                     table.addCell(cell4);
                        String str5="ΗΜΕΡ/ΝΙΑ";
                     
                     PdfPCell cell5 = new PdfPCell (new Paragraph (str5,fonty2));
                      
                     table.addCell(cell5);
                        String str6="ΩΡΑ"
                                + "ΕΝΑΡΞΗΣ";
                     
                     PdfPCell cell6 = new PdfPCell (new Paragraph (str6,fonty2));
                   
                     table.addCell(cell6);
                        String str7="ΩΡΑ"
                               + " ΛΗΞΗΣ";
                     
                     PdfPCell cell7 = new PdfPCell (new Paragraph (str7,fonty2));
                    
                     table.addCell(cell7);
                        String str8="ΠΕΡΙΕΧΟΜΕΝΟ ΕΚΠΑΙΔΕΥΣΗΣ";
                     
                     PdfPCell cell8 = new PdfPCell (new Paragraph (str8,fonty2));
                  
                     table.addCell(cell8);
                        String str9="ΕΚΠΑΙΔΕΥΤΗΣ";
                     
                     PdfPCell cell9 = new PdfPCell (new Paragraph (str9,fonty2));
                   
                     table.addCell(cell9);
                        String str10="ΑΡ."
                               + " ΣΕΛΙΔΑΣ";
                     
                     PdfPCell cell10 = new PdfPCell (new Paragraph (str10,fonty2));
                    
                     
                     table.addCell(cell10);
                        String str11="ΑΡ."
                               + " ΓΡΑΜΜΗΣ";
                     
                     PdfPCell cell11 = new PdfPCell (new Paragraph (str11,fonty2));
                    
                     table.addCell(cell11);
                     table.addCell("1");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str12="ΟΡΙΣΜΟΙ ΔΙΑΣΤΑΣΕΙΣ ΜΑΖΕΣ";
                     
                     PdfPCell cell12 = new PdfPCell (new Paragraph (str12,fonty2));
                   
                      table.addCell(cell12);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                      table.addCell("2");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str13="ΕΞΟΠΛΙΣΜΟΣ ΟΧΗΜΑΤΟΣ";
                     
                     PdfPCell cell13 = new PdfPCell (new Paragraph (str13,fonty2));
                   
                      table.addCell(cell13);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                      table.addCell("3");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str14="ΙΔΙΑΙΤΕΡΟΤΗΤΕΣ ΤΟΥ ΦΟΡΤΗΓΟΥ"
                                          + "ΚΑΙ ΤΗΣ ΟΔΗΓΗΣΗΣ ΤΟΥ";
                     
                     PdfPCell cell14 = new PdfPCell (new Paragraph (str14,fonty2));
                    
                      table.addCell(cell14);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                      table.addCell("4");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str15="ΠΡΟΥΠΟΘΕΣΕΙΣ ΧΟΡΗΓΗΣΗΣ"
                               + "ΑΔΕΙΑΣ ΟΔΗΓΗΣΗΣ ΦΟΡΤΗΓΟΥ";
                     
                     PdfPCell cell15 = new PdfPCell (new Paragraph (str15,fonty2));
                     
                      table.addCell(cell15);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                      table.addCell("5");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str16="ΦΟΡΤΩΣΗ ΚΑΙ ΜΕΤΑΦΟΡΑ"
                                          + "ΕΜΠΟΡΕΥΜΑΤΩΝ";
                     
                     PdfPCell cell16 = new PdfPCell (new Paragraph (str16,fonty2));
                   
                      table.addCell(cell16);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                      table.addCell("6");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str17="ΚΥΚΛΟΦΟΡΙΑ ΦΟΡΤΗΓΟΥ";
                     
                     PdfPCell cell17 = new PdfPCell (new Paragraph (str17,fonty2));
                  
                      table.addCell(cell17);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                      table.addCell("7");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str18="ΜΗΧΑΝΟΛΟΓΙΚΑ ΣΤΟΙΧΕΙΑ ΦΟΡΤΗΓΟΥ";
                     
                     PdfPCell cell18 = new PdfPCell (new Paragraph (str18,fonty2));
                     
                      table.addCell(cell18);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                      table.addCell("8");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str19="ΖΕΥΞΗ ΑΠΟΖΕΥΞΗ ΦΟΡΤΗΓΩΝ"
                               + "ΑΡΘΡΩΤΩΝ ΟΧΗΜΑΤΩΝ ΚΑΙ"
                               + "ΣΥΡΜΩΝ";
                     
                     PdfPCell cell19 = new PdfPCell (new Paragraph (str19,fonty2));
                   
                      table.addCell(cell19);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                      table.addCell("9");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str20="ΣΥΝΤΗΡΗΣΗ ΟΧΗΜΑΤΟΣ-"
                               + "ΕΛΕΓΧΟΙ";
                     
                     PdfPCell cell20 = new PdfPCell (new Paragraph (str20,fonty2));
                  
                      table.addCell(cell20);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                      table.addCell("10");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str21="ΥΠΟΧΡΕΩΣΕΙΣ ΟΔΗΓΟΥΙ"
                                          + "ΦΟΡΤΗΓΩΝ-ΝΟΜΙΚΕΣ ΕΥΘΥΝΕΣ";
                     
                     PdfPCell cell21 = new PdfPCell (new Paragraph (str21,fonty2));
                
                      table.addCell(cell21);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                      table.addCell("11");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str22="ΟΔΙΚΕΣ ΜΕΤΑΦΟΡΕΣ"
                                          + "ΕΜΠΟΡΕΥΜΑΤΩΝ";
                     
                     PdfPCell cell22 = new PdfPCell (new Paragraph (str22,fonty2));
              
                      table.addCell(cell22);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                      table.addCell("12");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str23="ΕΚΠΑΙΔΕΥΣΗ ΚΑΙ"
                               + "ΕΞΕΤΑΣΗ ΥΠΟΨΗΦΙΩΝ ΟΔΗΓΩΝ";
                     
                     PdfPCell cell23 = new PdfPCell (new Paragraph (str23,fonty2));
                   
                      table.addCell(cell23);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                      table.addCell("13");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str24="ΦΟΡΤΗΓΑ ΟΧΗΜΑΤΑ ΕΙΔΙΚΗΣ"
                               + "ΧΡΗΣΗΣ";
                     
                     PdfPCell cell24 = new PdfPCell (new Paragraph (str24,fonty2));
                   
                      table.addCell(cell24);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                      table.addCell("14");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str25="ΕΙΔΙΚΕΣ ΣΗΜΑΝΣΕΙΣ";
                     
                     PdfPCell cell25 = new PdfPCell (new Paragraph (str25,fonty2));
                   
                      table.addCell(cell25);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                      table.addCell("15");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str26="ΠΑΡΑΒΑΣΕΙΣ ΠΟΙΝΟΛΟΓΙΟ";
                     
                     PdfPCell cell26 = new PdfPCell (new Paragraph (str26,fonty2));
                   
                      table.addCell(cell26);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                      table.addCell("16");
                     table.addCell("");
                     table.addCell("");
                     table.addCell("");
                       String str27="ΥΠΟΛΟΓΙΣΤΗΣ";
                     
                     PdfPCell cell27 = new PdfPCell (new Paragraph (str27,fonty2));
                  
                      table.addCell(cell27);
                       table.addCell("");
                     table.addCell("");
                     table.addCell("");
                          document.add(table);
                          
                           document.add(new Paragraph("                                                                                                           ......../........../2013"));
                      document.add(new Paragraph("                                                                                                                Ο Δ/ΝΤΗΣ ΣΠΟΥΔΩΝ ΚΕΘΕΥΟ"
                              + "                                                                                                                                                 ( Σφραγιδα - Υπογραφη)",fonty2));
                      
                    
                     


                     document.close();
                      Toolkit.getDefaultToolkit().beep();
             JOptionPane.showMessageDialog(null,Message);
        } catch (SQLException ex) {
            Logger.getLogger(Lorry.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Lorry.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Lorry.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Bus.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Search.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        int selectedOption = JOptionPane.showConfirmDialog(null, "Do you wanna close the window?", "Choose", 
                                  JOptionPane.YES_NO_OPTION); 
        if (selectedOption == JOptionPane.YES_OPTION) 
        {
            setVisible(false);
            dispose();
        }
        if (selectedOption == JOptionPane.NO_OPTION){
    
}
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lorry().setVisible(true);
            }
        });
    }
    
      private void displayresults(ResultSet result) throws SQLException{
        
        if(result.next()){
            str28=result.getString(1);
            str29=result.getString(2);
           
            
            
            
        }
        
        
    }
      private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("car.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Result;
    private javax.swing.JTextField Search;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
